### PR TITLE
[WIP] Constexpr type_index

### PR DESCRIPTION
**Pull request by klemens-morgenstern**
Implemented an alpha, currently gcc only. If you think the integration is alright, I'll add other toolchains.

It seems that my #if don't work on MSVC 2015.

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
I don't think this can be build to work with C++11, because the __PRETTY_FUNCTION__ needs to be in a method. I can't put it in the expansion method (ctti::impl), because I then have NO clue where the index list ends. That might be implemented, but then we completely screw up compile times.

**Comment by klemens-morgenstern** [comment]
Ok, I don't get why it doesn't work, gcc-5 doesn find `ctti_skip_size_at_begin_type` which I declared. Works with mingw. Strange.

**Comment by apolukhin** [comment]
I've applied mix of your, mine and Manu Sánchez ideas to the constexpr14 branch. A few more more thing remain to do.

Thanks for the pull request!

**Comment by klemens-morgenstern** [comment]
Always a pleasure. Please tell me if you have a working version - this provides so many evil things to do with boost.variant.

**Pull request closed without merging**
